// Mock listing data for development/testing — realistic Indian real estate data
// Prices are calibrated to actual 2025-2026 market rates per locality
const MOCK_LISTINGS = {
    'Delhi NCR': [
        { title: '3 BHK Apartment in Dwarka', price: '85 Lac', area: '1450 sq.ft', locality: 'Dwarka', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 4, totalFloors: 12, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'power_backup'], builder: 'DLF', lat: 28.5921, lng: 77.0460 },
        { title: '2 BHK Flat in Rohini', price: '55 Lac', area: '950 sq.ft', locality: 'Rohini', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 14, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'CGHS', lat: 28.7325, lng: 77.1148 },
        { title: '4 BHK Villa in Vasant Kunj', price: '3.2 Cr', area: '3200 sq.ft', locality: 'Vasant Kunj', type: 'Villa', bedrooms: 4, bathrooms: 4, floor: 0, totalFloors: 3, age: 8, furnishing: 'furnished', amenities: ['parking', 'garden', 'security', 'power_backup', 'water_supply'], builder: 'Private', lat: 28.5194, lng: 77.1568 },
        { title: '1 BHK Studio in Saket', price: '35 Lac', area: '550 sq.ft', locality: 'Saket', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 3, totalFloors: 8, age: 2, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym'], builder: 'Unitech', lat: 28.5244, lng: 77.2090 },
        { title: '3 BHK in Greater Kailash', price: '1.8 Cr', area: '1800 sq.ft', locality: 'Greater Kailash', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 5, totalFloors: 10, age: 10, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'club_house', 'swimming_pool'], builder: 'Ansal', lat: 28.5488, lng: 77.2405 },
        { title: 'Commercial Space in Connaught Place', price: '5.5 Cr', area: '2000 sq.ft', locality: 'Connaught Place', type: 'Commercial', bedrooms: 0, bathrooms: 2, floor: 2, totalFloors: 6, age: 15, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'power_backup', 'fire_safety'], builder: 'NDMC', lat: 28.6315, lng: 77.2167 },
        { title: 'Plot in Chattarpur', price: '2.5 Cr', area: '2400 sq.ft', locality: 'Chattarpur', type: 'Land', bedrooms: 0, bathrooms: 0, floor: 0, totalFloors: 0, age: 0, furnishing: 'unfurnished', amenities: [], builder: '', lat: 28.5014, lng: 77.1804 },
        { title: '2 BHK in Lajpat Nagar', price: '72 Lac', area: '1100 sq.ft', locality: 'Lajpat Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 6, totalFloors: 9, age: 7, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 28.5700, lng: 77.2400 },
        { title: '3 BHK in Hauz Khas', price: '2.4 Cr', area: '1500 sq.ft', locality: 'Hauz Khas', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 3, totalFloors: 6, age: 12, furnishing: 'furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 28.5494, lng: 77.2001 },
        { title: '2 BHK in Defence Colony', price: '2.0 Cr', area: '1000 sq.ft', locality: 'Defence Colony', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 2, totalFloors: 4, age: 20, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'DDA', lat: 28.5729, lng: 77.2310 },
        { title: '2 BHK in Pitampura', price: '65 Lac', area: '900 sq.ft', locality: 'Pitampura', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 12, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Ashiana', lat: 28.7033, lng: 77.1340 },
        { title: '3 BHK in Mayur Vihar', price: '1.1 Cr', area: '1300 sq.ft', locality: 'Mayur Vihar', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 6, totalFloors: 14, age: 6, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'power_backup'], builder: 'DDA', lat: 28.6071, lng: 77.2988 },
        { title: '1 BHK in Karol Bagh', price: '52 Lac', area: '550 sq.ft', locality: 'Karol Bagh', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 4, totalFloors: 6, age: 15, furnishing: 'unfurnished', amenities: ['parking'], builder: 'Private', lat: 28.6514, lng: 77.1907 },
        { title: '3 BHK in South Extension', price: '2.2 Cr', area: '1400 sq.ft', locality: 'South Extension', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 3, totalFloors: 5, age: 18, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 28.5728, lng: 77.2225 },
        { title: '2 BHK in Janakpuri', price: '68 Lac', area: '850 sq.ft', locality: 'Janakpuri', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 10, age: 5, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 28.6172, lng: 77.0844 },
    ],
    'Mumbai': [
        { title: '2 BHK in Andheri West', price: '1.4 Cr', area: '850 sq.ft', locality: 'Andheri West', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 12, totalFloors: 25, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'Lodha', lat: 19.1364, lng: 72.8296 },
        { title: '3 BHK in Powai', price: '2.8 Cr', area: '1350 sq.ft', locality: 'Powai', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 18, totalFloors: 30, age: 5, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security', 'jogging_track'], builder: 'Hiranandani', lat: 19.1176, lng: 72.9060 },
        { title: '1 BHK in Dadar', price: '95 Lac', area: '450 sq.ft', locality: 'Dadar', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 5, totalFloors: 7, age: 20, furnishing: 'unfurnished', amenities: ['lift'], builder: 'Private', lat: 19.0178, lng: 72.8478 },
        { title: '4 BHK Sea View in Bandra', price: '8.5 Cr', area: '2200 sq.ft', locality: 'Bandra West', type: 'Apartment', bedrooms: 4, bathrooms: 4, floor: 22, totalFloors: 35, age: 2, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security', 'concierge'], builder: 'Oberoi Realty', lat: 19.0596, lng: 72.8295 },
        { title: '2 BHK in Thane', price: '78 Lac', area: '750 sq.ft', locality: 'Thane West', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 20, age: 4, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security', 'play_area'], builder: 'Rustomjee', lat: 19.2183, lng: 72.9781 },
        { title: 'Commercial Office in BKC', price: '12 Cr', area: '3000 sq.ft', locality: 'BKC', type: 'Commercial', bedrooms: 0, bathrooms: 3, floor: 15, totalFloors: 40, age: 1, furnishing: 'furnished', amenities: ['parking', 'lift', 'power_backup', 'fire_safety', 'cctv'], builder: 'Adani', lat: 19.0660, lng: 72.8693 },
        { title: '3 BHK in Malad West', price: '1.1 Cr', area: '1050 sq.ft', locality: 'Malad West', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 10, totalFloors: 18, age: 6, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'garden'], builder: 'Runwal', lat: 19.1874, lng: 72.8484 },
        { title: '2 BHK in Bandra East', price: '1.8 Cr', area: '700 sq.ft', locality: 'Bandra East', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 14, age: 10, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Mahindra', lat: 19.0607, lng: 72.8411 },
        { title: '3 BHK in Worli', price: '6.5 Cr', area: '1600 sq.ft', locality: 'Worli', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 28, totalFloors: 45, age: 1, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security', 'concierge'], builder: 'Lodha', lat: 19.0177, lng: 72.8150 },
        { title: '1 BHK in Goregaon West', price: '72 Lac', area: '500 sq.ft', locality: 'Goregaon West', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 6, totalFloors: 15, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Oberoi', lat: 19.1663, lng: 72.8491 },
        { title: '2 BHK in Borivali West', price: '1.0 Cr', area: '700 sq.ft', locality: 'Borivali West', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 10, totalFloors: 18, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'gym'], builder: 'Rustomjee', lat: 19.2290, lng: 72.8561 },
        { title: '2 BHK in Chembur', price: '1.3 Cr', area: '750 sq.ft', locality: 'Chembur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 8, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 19.0522, lng: 72.8964 },
        { title: '3 BHK in Lower Parel', price: '4.5 Cr', area: '1400 sq.ft', locality: 'Lower Parel', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 20, totalFloors: 35, age: 3, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security'], builder: 'Lodha', lat: 18.9986, lng: 72.8301 },
        { title: '2 BHK in Kandivali West', price: '88 Lac', area: '650 sq.ft', locality: 'Kandivali West', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 16, age: 6, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Runwal', lat: 19.2040, lng: 72.8498 },
        { title: '1 BHK in Kharghar', price: '52 Lac', area: '550 sq.ft', locality: 'Kharghar', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 9, totalFloors: 20, age: 2, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Adhiraj', lat: 19.0474, lng: 73.0627 },
        { title: '3 BHK in Ghatkopar', price: '1.6 Cr', area: '950 sq.ft', locality: 'Ghatkopar', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 4, totalFloors: 10, age: 12, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 19.0860, lng: 72.9081 },
        { title: '2 BHK in Mulund', price: '1.0 Cr', area: '700 sq.ft', locality: 'Mulund', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 6, totalFloors: 14, age: 7, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security', 'garden'], builder: 'Runwal', lat: 19.1726, lng: 72.9561 },
        { title: '2 BHK in Navi Mumbai', price: '62 Lac', area: '800 sq.ft', locality: 'Navi Mumbai', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 11, totalFloors: 22, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security', 'play_area'], builder: 'Indiabulls', lat: 19.0330, lng: 73.0297 },
    ],
    'Bangalore': [
        { title: '3 BHK in Whitefield', price: '1.2 Cr', area: '1550 sq.ft', locality: 'Whitefield', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 6, totalFloors: 15, age: 4, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security'], builder: 'Prestige', lat: 12.9698, lng: 77.7500 },
        { title: '2 BHK in Koramangala', price: '95 Lac', area: '1100 sq.ft', locality: 'Koramangala', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 8, age: 8, furnishing: 'furnished', amenities: ['parking', 'lift', 'security'], builder: 'Sobha', lat: 12.9352, lng: 77.6245 },
        { title: '4 BHK Villa in Sarjapur', price: '2.5 Cr', area: '3000 sq.ft', locality: 'Sarjapur Road', type: 'Villa', bedrooms: 4, bathrooms: 4, floor: 0, totalFloors: 3, age: 2, furnishing: 'furnished', amenities: ['parking', 'garden', 'security', 'swimming_pool', 'club_house', 'play_area'], builder: 'Brigade', lat: 12.8680, lng: 77.6833 },
        { title: '2 BHK in Electronic City', price: '52 Lac', area: '950 sq.ft', locality: 'Electronic City', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 9, totalFloors: 16, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security', 'power_backup'], builder: 'Puravankara', lat: 12.8399, lng: 77.6770 },
        { title: '3 BHK in HSR Layout', price: '1.5 Cr', area: '1400 sq.ft', locality: 'HSR Layout', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 3, totalFloors: 6, age: 6, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'gym'], builder: 'Salarpuria', lat: 12.9116, lng: 77.6474 },
        { title: 'Plot in Devanahalli', price: '80 Lac', area: '1200 sq.ft', locality: 'Devanahalli', type: 'Land', bedrooms: 0, bathrooms: 0, floor: 0, totalFloors: 0, age: 0, furnishing: 'unfurnished', amenities: [], builder: '', lat: 13.2473, lng: 77.7139 },
        { title: '1 BHK in Marathahalli', price: '42 Lac', area: '650 sq.ft', locality: 'Marathahalli', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 5, totalFloors: 12, age: 4, furnishing: 'furnished', amenities: ['parking', 'lift', 'security'], builder: 'Gopalan', lat: 12.9562, lng: 77.7019 },
        { title: '3 BHK in Indiranagar', price: '2.0 Cr', area: '1450 sq.ft', locality: 'Indiranagar', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 3, totalFloors: 5, age: 10, furnishing: 'furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 12.9784, lng: 77.6408 },
        { title: '2 BHK in Hebbal', price: '85 Lac', area: '1050 sq.ft', locality: 'Hebbal', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 15, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Prestige', lat: 13.0358, lng: 77.5970 },
        { title: '2 BHK in JP Nagar', price: '72 Lac', area: '950 sq.ft', locality: 'JP Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 8, age: 7, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 12.8912, lng: 77.5853 },
        { title: '3 BHK in Jayanagar', price: '1.4 Cr', area: '1300 sq.ft', locality: 'Jayanagar', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 2, totalFloors: 4, age: 15, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 12.9308, lng: 77.5838 },
        { title: '2 BHK in Bellandur', price: '65 Lac', area: '1000 sq.ft', locality: 'Bellandur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 10, totalFloors: 18, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'gym', 'security', 'swimming_pool'], builder: 'Sobha', lat: 12.9260, lng: 77.6762 },
        { title: '2 BHK in Yelahanka', price: '48 Lac', area: '850 sq.ft', locality: 'Yelahanka', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Puravankara', lat: 13.1007, lng: 77.5963 },
        { title: '3 BHK in Bannerghatta Road', price: '82 Lac', area: '1250 sq.ft', locality: 'Bannerghatta Road', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 8, totalFloors: 14, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'gym'], builder: 'Salarpuria', lat: 12.8876, lng: 77.5963 },
        { title: '2 BHK in Rajajinagar', price: '90 Lac', area: '1000 sq.ft', locality: 'Rajajinagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 3, totalFloors: 6, age: 12, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 12.9867, lng: 77.5527 },
        { title: '1 BHK in Hennur', price: '35 Lac', area: '600 sq.ft', locality: 'Hennur', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 6, totalFloors: 14, age: 2, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Provident', lat: 13.0450, lng: 77.6410 },
    ],
    'Pune': [
        { title: '2 BHK in Hinjewadi', price: '62 Lac', area: '900 sq.ft', locality: 'Hinjewadi', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 15, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Kolte Patil', lat: 18.5912, lng: 73.7390 },
        { title: '3 BHK in Baner', price: '1.1 Cr', area: '1350 sq.ft', locality: 'Baner', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 10, totalFloors: 18, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house'], builder: 'Panchshil', lat: 18.5590, lng: 73.7868 },
        { title: '3 BHK in Kothrud', price: '95 Lac', area: '1200 sq.ft', locality: 'Kothrud', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 4, totalFloors: 8, age: 10, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'DSK', lat: 18.5074, lng: 73.8077 },
        { title: '4 BHK Villa in Koregaon Park', price: '3.5 Cr', area: '2800 sq.ft', locality: 'Koregaon Park', type: 'Villa', bedrooms: 4, bathrooms: 3, floor: 0, totalFloors: 2, age: 7, furnishing: 'furnished', amenities: ['parking', 'garden', 'security', 'power_backup'], builder: 'Private', lat: 18.5362, lng: 73.8930 },
        { title: '1 BHK in Wakad', price: '38 Lac', area: '600 sq.ft', locality: 'Wakad', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 3, totalFloors: 10, age: 2, furnishing: 'unfurnished', amenities: ['parking', 'lift'], builder: 'Kumar Properties', lat: 18.5990, lng: 73.7630 },
        { title: '2 BHK in Kalyani Nagar', price: '1.2 Cr', area: '1050 sq.ft', locality: 'Kalyani Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 6, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'gym'], builder: 'Panchshil', lat: 18.5535, lng: 73.9010 },
        { title: '3 BHK in Aundh', price: '1.2 Cr', area: '1300 sq.ft', locality: 'Aundh', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 6, totalFloors: 10, age: 8, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Rohan', lat: 18.5602, lng: 73.8080 },
        { title: '2 BHK in Viman Nagar', price: '85 Lac', area: '950 sq.ft', locality: 'Viman Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 15, age: 4, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Goel Ganga', lat: 18.5679, lng: 73.9143 },
        { title: '2 BHK in Hadapsar', price: '48 Lac', area: '850 sq.ft', locality: 'Hadapsar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 9, totalFloors: 16, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Amanora', lat: 18.5018, lng: 73.9260 },
        { title: '2 BHK in Kharadi', price: '68 Lac', area: '900 sq.ft', locality: 'Kharadi', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 12, totalFloors: 20, age: 2, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'EON', lat: 18.5520, lng: 73.9400 },
        { title: '3 BHK in Magarpatta', price: '1.05 Cr', area: '1200 sq.ft', locality: 'Magarpatta', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 7, totalFloors: 14, age: 8, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'club_house', 'gym'], builder: 'Magarpatta City', lat: 18.5131, lng: 73.9280 },
        { title: '2 BHK in Bavdhan', price: '58 Lac', area: '800 sq.ft', locality: 'Bavdhan', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Paranjape', lat: 18.5195, lng: 73.7770 },
        { title: '1 BHK in Wagholi', price: '28 Lac', area: '600 sq.ft', locality: 'Wagholi', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 4, totalFloors: 10, age: 2, furnishing: 'unfurnished', amenities: ['parking', 'lift'], builder: 'Private', lat: 18.5771, lng: 73.9769 },
    ],
    'Hyderabad': [
        { title: '3 BHK in Gachibowli', price: '1.05 Cr', area: '1500 sq.ft', locality: 'Gachibowli', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 8, totalFloors: 20, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security'], builder: 'My Home', lat: 17.4400, lng: 78.3489 },
        { title: '2 BHK in Madhapur', price: '72 Lac', area: '1100 sq.ft', locality: 'Madhapur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 4, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'power_backup'], builder: 'Aparna', lat: 17.4486, lng: 78.3908 },
        { title: '2 BHK in Kukatpally', price: '48 Lac', area: '950 sq.ft', locality: 'Kukatpally', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 6, totalFloors: 14, age: 5, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Ramky', lat: 17.4947, lng: 78.3996 },
        { title: '4 BHK in Jubilee Hills', price: '4.2 Cr', area: '3500 sq.ft', locality: 'Jubilee Hills', type: 'Villa', bedrooms: 4, bathrooms: 4, floor: 0, totalFloors: 3, age: 6, furnishing: 'furnished', amenities: ['parking', 'garden', 'security', 'swimming_pool', 'power_backup'], builder: 'Private', lat: 17.4325, lng: 78.4073 },
        { title: '3 BHK in Kondapur', price: '85 Lac', area: '1300 sq.ft', locality: 'Kondapur', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 10, totalFloors: 18, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Aparna', lat: 17.4642, lng: 78.3697 },
        { title: '3 BHK in Banjara Hills', price: '2.5 Cr', area: '2000 sq.ft', locality: 'Banjara Hills', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 4, totalFloors: 8, age: 10, furnishing: 'furnished', amenities: ['parking', 'security', 'power_backup'], builder: 'Private', lat: 17.4156, lng: 78.4347 },
        { title: '2 BHK in Financial District', price: '70 Lac', area: '1000 sq.ft', locality: 'Financial District', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 14, totalFloors: 25, age: 2, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'My Home', lat: 17.4210, lng: 78.3390 },
        { title: '2 BHK in Miyapur', price: '42 Lac', area: '900 sq.ft', locality: 'Miyapur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Ramky', lat: 17.4969, lng: 78.3548 },
        { title: '3 BHK in Kokapet', price: '1.1 Cr', area: '1500 sq.ft', locality: 'Kokapet', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 12, totalFloors: 22, age: 1, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security'], builder: 'Prestige', lat: 17.4080, lng: 78.3240 },
        { title: '2 BHK in Begumpet', price: '78 Lac', area: '950 sq.ft', locality: 'Begumpet', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 3, totalFloors: 6, age: 12, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 17.4434, lng: 78.4685 },
        { title: '2 BHK in Manikonda', price: '52 Lac', area: '950 sq.ft', locality: 'Manikonda', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 14, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'SMR', lat: 17.4110, lng: 78.3870 },
    ],
    'Chennai': [
        { title: '2 BHK in OMR', price: '58 Lac', area: '1000 sq.ft', locality: 'OMR', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 12, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Casagrand', lat: 12.9010, lng: 80.2279 },
        { title: '3 BHK in Adyar', price: '1.6 Cr', area: '1400 sq.ft', locality: 'Adyar', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 3, totalFloors: 6, age: 12, furnishing: 'unfurnished', amenities: ['parking', 'security'], builder: 'Private', lat: 13.0012, lng: 80.2565 },
        { title: '3 BHK in Velachery', price: '75 Lac', area: '1200 sq.ft', locality: 'Velachery', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 8, totalFloors: 15, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'play_area'], builder: 'TVS Emerald', lat: 12.9815, lng: 80.2180 },
        { title: '3 BHK in Anna Nagar', price: '1.3 Cr', area: '1300 sq.ft', locality: 'Anna Nagar', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 4, totalFloors: 8, age: 8, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Radiance', lat: 13.0850, lng: 80.2101 },
        { title: '2 BHK in T Nagar', price: '1.2 Cr', area: '900 sq.ft', locality: 'T Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 3, totalFloors: 5, age: 15, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 13.0418, lng: 80.2341 },
        { title: '2 BHK in Sholinganallur', price: '62 Lac', area: '950 sq.ft', locality: 'Sholinganallur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 9, totalFloors: 16, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Casagrand', lat: 12.9013, lng: 80.2275 },
        { title: '3 BHK in Guindy', price: '1.0 Cr', area: '1200 sq.ft', locality: 'Guindy', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 5, totalFloors: 10, age: 10, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Private', lat: 13.0067, lng: 80.2206 },
        { title: '2 BHK in Nungambakkam', price: '1.4 Cr', area: '1000 sq.ft', locality: 'Nungambakkam', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 7, age: 12, furnishing: 'furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 13.0569, lng: 80.2425 },
        { title: '2 BHK in Tambaram', price: '35 Lac', area: '800 sq.ft', locality: 'Tambaram', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 3, totalFloors: 8, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift'], builder: 'Alliance', lat: 12.9249, lng: 80.1000 },
        { title: '3 BHK in Thiruvanmiyur', price: '1.3 Cr', area: '1350 sq.ft', locality: 'Thiruvanmiyur', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 5, totalFloors: 8, age: 7, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Appaswamy', lat: 12.9830, lng: 80.2621 },
    ],
    'Gurgaon': [
        { title: '3 BHK in Golf Course Road', price: '2.2 Cr', area: '1800 sq.ft', locality: 'Golf Course Road', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 15, totalFloors: 30, age: 4, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security', 'concierge'], builder: 'DLF', lat: 28.4403, lng: 77.1022 },
        { title: '2 BHK in Sohna Road', price: '55 Lac', area: '1050 sq.ft', locality: 'Sohna Road', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 9, totalFloors: 20, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Godrej', lat: 28.3949, lng: 77.0640 },
        { title: '4 BHK in DLF Phase 5', price: '3.8 Cr', area: '2500 sq.ft', locality: 'DLF Phase 5', type: 'Apartment', bedrooms: 4, bathrooms: 4, floor: 20, totalFloors: 35, age: 6, furnishing: 'furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security', 'jogging_track', 'sports_facility'], builder: 'DLF', lat: 28.4595, lng: 77.0966 },
        { title: '2 BHK in Sector 56', price: '82 Lac', area: '1000 sq.ft', locality: 'Sector 56', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 10, totalFloors: 18, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security', 'gym'], builder: 'Unitech', lat: 28.4282, lng: 77.0880 },
        { title: '3 BHK in Dwarka Expressway', price: '90 Lac', area: '1400 sq.ft', locality: 'Dwarka Expressway', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 12, totalFloors: 25, age: 2, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'Godrej', lat: 28.4190, lng: 77.0320 },
        { title: '2 BHK in Sector 82', price: '45 Lac', area: '850 sq.ft', locality: 'Sector 82', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 8, totalFloors: 16, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Emaar', lat: 28.3800, lng: 76.9900 },
        { title: '3 BHK in DLF Phase 1', price: '1.5 Cr', area: '1350 sq.ft', locality: 'DLF Phase 1', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 5, totalFloors: 10, age: 15, furnishing: 'semi_furnished', amenities: ['parking', 'security', 'power_backup'], builder: 'DLF', lat: 28.4733, lng: 77.0930 },
    ],
    'Noida': [
        { title: '3 BHK in Sector 150', price: '72 Lac', area: '1400 sq.ft', locality: 'Sector 150', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 10, totalFloors: 22, age: 2, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'Jaypee', lat: 28.4601, lng: 77.3532 },
        { title: '2 BHK in Sector 75', price: '48 Lac', area: '1000 sq.ft', locality: 'Sector 75', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 18, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Supertech', lat: 28.5721, lng: 77.3711 },
        { title: '3 BHK in Sector 137', price: '78 Lac', area: '1350 sq.ft', locality: 'Sector 137', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 14, totalFloors: 25, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'Jaypee', lat: 28.4850, lng: 77.3600 },
        { title: '2 BHK in Sector 44', price: '72 Lac', area: '950 sq.ft', locality: 'Sector 44', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 8, age: 10, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'DDA', lat: 28.5700, lng: 77.3380 },
        { title: '3 BHK in Noida Expressway', price: '85 Lac', area: '1400 sq.ft', locality: 'Noida Expressway', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 16, totalFloors: 28, age: 2, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'club_house', 'security'], builder: 'ATS', lat: 28.5100, lng: 77.3700 },
        { title: '2 BHK in Greater Noida West', price: '30 Lac', area: '850 sq.ft', locality: 'Greater Noida West', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 9, totalFloors: 18, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Gaurs', lat: 28.5900, lng: 77.4300 },
    ],
    'Ahmedabad': [
        { title: '3 BHK in SG Highway', price: '68 Lac', area: '1350 sq.ft', locality: 'SG Highway', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 8, totalFloors: 15, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security', 'garden'], builder: 'Adani Realty', lat: 23.0469, lng: 72.5297 },
        { title: '2 BHK in Prahlad Nagar', price: '52 Lac', area: '1050 sq.ft', locality: 'Prahlad Nagar', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 10, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Safal', lat: 23.0145, lng: 72.5070 },
        { title: '3 BHK in Satellite', price: '78 Lac', area: '1200 sq.ft', locality: 'Satellite', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 6, totalFloors: 10, age: 8, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Shivalik', lat: 23.0194, lng: 72.5242 },
        { title: '2 BHK in Bopal', price: '38 Lac', area: '900 sq.ft', locality: 'Bopal', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 10, age: 3, furnishing: 'unfurnished', amenities: ['parking', 'lift', 'security'], builder: 'Siddhi', lat: 23.0300, lng: 72.4650 },
        { title: '3 BHK in Navrangpura', price: '1.0 Cr', area: '1300 sq.ft', locality: 'Navrangpura', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 3, totalFloors: 6, age: 15, furnishing: 'semi_furnished', amenities: ['parking', 'security'], builder: 'Private', lat: 23.0393, lng: 72.5567 },
        { title: '2 BHK in Bodakdev', price: '62 Lac', area: '950 sq.ft', locality: 'Bodakdev', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 7, totalFloors: 12, age: 4, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Adani', lat: 23.0367, lng: 72.5011 },
        { title: '1 BHK in Gota', price: '22 Lac', area: '600 sq.ft', locality: 'Gota', type: 'Apartment', bedrooms: 1, bathrooms: 1, floor: 3, totalFloors: 8, age: 2, furnishing: 'unfurnished', amenities: ['parking', 'lift'], builder: 'Shree', lat: 23.1100, lng: 72.5370 },
    ],
    'Kolkata': [
        { title: '3 BHK in Rajarhat', price: '55 Lac', area: '1250 sq.ft', locality: 'Rajarhat', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 6, totalFloors: 14, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'security'], builder: 'Ambuja Neotia', lat: 22.6368, lng: 88.4579 },
        { title: '2 BHK in Salt Lake', price: '48 Lac', area: '1000 sq.ft', locality: 'Salt Lake', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 4, totalFloors: 8, age: 7, furnishing: 'unfurnished', amenities: ['parking', 'security'], builder: 'South City', lat: 22.5809, lng: 88.4148 },
        { title: '3 BHK in New Town', price: '58 Lac', area: '1200 sq.ft', locality: 'New Town', type: 'Apartment', bedrooms: 3, bathrooms: 2, floor: 8, totalFloors: 16, age: 3, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'gym', 'swimming_pool', 'security'], builder: 'Tata', lat: 22.5958, lng: 88.4674 },
        { title: '3 BHK in Alipore', price: '2.0 Cr', area: '1800 sq.ft', locality: 'Alipore', type: 'Apartment', bedrooms: 3, bathrooms: 3, floor: 3, totalFloors: 6, age: 10, furnishing: 'furnished', amenities: ['parking', 'security', 'power_backup'], builder: 'Private', lat: 22.5320, lng: 88.3372 },
        { title: '2 BHK in EM Bypass', price: '62 Lac', area: '1000 sq.ft', locality: 'EM Bypass', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 6, totalFloors: 12, age: 5, furnishing: 'semi_furnished', amenities: ['parking', 'lift', 'security'], builder: 'Merlin', lat: 22.5180, lng: 88.3980 },
        { title: '2 BHK in Jadavpur', price: '52 Lac', area: '900 sq.ft', locality: 'Jadavpur', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 3, totalFloors: 7, age: 8, furnishing: 'unfurnished', amenities: ['parking', 'security'], builder: 'Private', lat: 22.4988, lng: 88.3711 },
        { title: '2 BHK in Howrah', price: '32 Lac', area: '850 sq.ft', locality: 'Howrah', type: 'Apartment', bedrooms: 2, bathrooms: 2, floor: 5, totalFloors: 10, age: 4, furnishing: 'unfurnished', amenities: ['parking', 'lift'], builder: 'PS Group', lat: 22.5958, lng: 88.2636 },
    ]
};

function getMockListingsForCity(city, source) {
    const listings = MOCK_LISTINGS[city] || [];
    return listings.map((l, idx) => ({
        source,
        sourceListingId: `${source}_${city.replace(/\s/g, '_').toLowerCase()}_${idx + 1}_${Date.now()}`,
        sourceUrl: `https://www.${source}.com/listing/${idx + 1}`,
        propertyType: l.type,
        city,
        locality: l.locality,
        geoLocation: {
            type: 'Point',
            coordinates: [l.lng, l.lat]
        },
        areaSqft: parseInt(l.area),
        bedrooms: l.bedrooms,
        bathrooms: l.bathrooms,
        floorNumber: l.floor,
        totalFloors: l.totalFloors,
        ageOfPropertyYears: l.age,
        listedPrice: parseIndianPrice(l.price),
        amenities: l.amenities,
        furnishingStatus: l.furnishing,
        rawData: { title: l.title, rawPrice: l.price, rawArea: l.area, builder: l.builder },
        scrapedAt: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000),
        listingDate: new Date(Date.now() - (Math.random() * 400 + 30) * 24 * 60 * 60 * 1000)
    }));
}

function parseIndianPrice(priceStr) {
    if (!priceStr) return 0;
    const str = priceStr.toString().trim().replace(/[₹,\s]/g, '');

    const crMatch = str.match(/^([\d.]+)\s*(?:Cr|Crore|cr)$/i);
    if (crMatch) return Math.round(parseFloat(crMatch[1]) * 10000000);

    const lacMatch = str.match(/^([\d.]+)\s*(?:L|Lac|Lakh|Lakhs|lac)$/i);
    if (lacMatch) return Math.round(parseFloat(lacMatch[1]) * 100000);

    const num = parseFloat(str.replace(/,/g, ''));
    return isNaN(num) ? 0 : Math.round(num);
}

module.exports = { MOCK_LISTINGS, getMockListingsForCity, parseIndianPrice };
